---
- hosts: all
  name: MariaDB
  become: yes
  become_method: sudo
  vars_files:
    - ../vars/vars.yml
  gather_facts: true
  vars:
  tasks:
    - name: install mariadb
      yum:
        name:
          - mariadb-server
          - MySQL-python
        state: latest
    - name: start mariadb
      service:
        name: mariadb
        enabled: true
        state: started
    - name: mysql_root_password
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        check_implicit_admin: true
        password: "{{ mysql_root_password }}"
        host: localhost